# Set of function to scrape tthe IMDb website
IMDb.root.link <- "https://www.imdb.com"

# connect to database
IMDb.Ghibli.Reviews <- collect(tbl(mydb, "IMDb.Ghibli.Reviews"))

# Scrapes information from the IMDb website
#
# @params title the movie title
#
# returns a named list containing information on the movie id, rating, rating count, and one review
getIMDbReview <- function(title) {
  q <- str_replace_all(title, "\\s", "+")
  search.html <- read_html(str_glue("https://www.imdb.com/find?q={q}", q = q))
  link <- search.html %>%
    html_node("td.result_text") %>%
    html_node("a") %>%
    html_attr("href")

  movie.html <- read_html(paste0(IMDb.root.link, link))

  rating <- movie.html %>%
    html_node("div.imdbRating") %>%
    html_node("span") %>%
    html_text()

  rating.count <- movie.html %>%
    html_node("div.imdbRating") %>%
    html_node("span.small") %>%
    html_text()

  review.text <- movie.html %>%
    html_node("div.user-comments") %>%
    html_node("span") %>%
    html_node("p") %>%
    html_text()

  id <- link %>%
    str_match("/title/[a-zA-Z0-9]+/") %>%
    as.vector()

  return(
    list(
      "id" = id,
      "rating" = rating,
      "ratingCount" = rating.count,
      "reviewText" = review.text
    )
  )
}

# Scrapes the meta critic review from the IMDb website
#
# @params id the id obtained via the getIMDbReview()
#
# returns a tibble containing the meta critic stats
getCriticReview <- function(id) {
  critic.html <- read_html(paste0(IMDb.root.link, id, "criticreviews"))

  critic.score <- critic.html %>%
    html_nodes("td.score") %>%
    html_node("span") %>%
    html_text()

  critic.name <- critic.html %>%
    html_nodes("td.review") %>%
    html_node("b") %>%
    html_node("span") %>%
    html_text()

  critic.text <- critic.html %>%
    html_nodes("td.review") %>%
    html_node("div.summary") %>%
    html_text()

  return(
    tibble(
      critic.name = critic.name,
      critic.score = as.numeric(critic.score),
      critic.text = critic.text
    )
  )
}


# Generates a bar plot of the meta critics
#
# @param id the id field in the table generated by getCriticReview()
#
# return plot
criticBarPlot <- function(id) {
  critic <- getCriticReview(id)
  ggplot(data = critic, aes(x = critic.name, y = critic.score, fill = critic.name)) +
    geom_bar(stat = "identity") +
    labs(x = "", y = "Score") +
    theme_minimal() +
    theme(
      axis.text.x = element_text(angle = 90),
      legend.position = "none"
    )
}

# Generates a word based on IMDb user reviews
# 
# @params conn database collection
# @params title film title
# @max_words max words in the word cloud
#
# return Word cloud plot
generateWordCloud <- function(title, max_words) {
  return(
    IMDb.Ghibli.Reviews %>% 
      filter(title == title) %>%
      unnest_tokens(word, review) %>%
      anti_join(stop_words) %>%
      group_by(word) %>%
      summarise(n = n()) %>% 
      with(wordcloud(
        word, n, min.freq = 2, max.words = max_words, random.order = FALSE,
        colors = brewer.pal(8, "Dark2"))
      )
  )
}

### Review n grams

# Gets review bigram
#
# @param title film title
#
# return sorted bigram df
getReviewBigram <- function(title) {
  bigram <- IMDb.Ghibli.Reviews %>%
    filter(title == title) %>%
    unnest_tokens(bigram, review, token = "ngrams", n = 2) %>%
    separate(bigram, c("word1", "word2"), sep = " ") %>%
    anti_join(stop_words, by = c("word1" = "word")) %>%
    anti_join(stop_words, by = c("word2" = "word")) %>%
    count(word1, word2, sort = TRUE) %>%
    head(10)
  return(bigram)
}

getReview3gram <- function(title) {
  trigram <- IMDb.Ghibli.Reviews %>%
    filter(title == title) %>%
    unnest_tokens(ngram, review, token = "ngrams", n = 3) %>%
    separate(ngram, c("word1", "word2", "word3"), sep = " ") %>%
    anti_join(stop_words, by = c("word1" = "word")) %>%
    anti_join(stop_words, by = c("word2" = "word")) %>%
    anti_join(stop_words, by = c("word3" = "word")) %>%
    count(word1, word2, word3, sort = TRUE) %>%
    head(10)
  return(trigram)
}

getReview4gram <- function(title) {
  quadgram <- IMDb.Ghibli.Reviews %>%
    filter(title == title) %>%
    unnest_tokens(ngram, review, token = "ngrams", n = 4) %>%
    separate(ngram, c("word1", "word2", "word3", "word4"), sep = " ") %>%
    anti_join(stop_words, by = c("word1" = "word")) %>%
    anti_join(stop_words, by = c("word2" = "word")) %>%
    anti_join(stop_words, by = c("word3" = "word")) %>%
    anti_join(stop_words, by = c("word4" = "word")) %>%
    count(word1, word2, word3, word4, sort = TRUE) %>%
    head(10)
  return(quadgram)
}

getReview5gram <- function(title) {
  pentagram <- IMDb.Ghibli.Reviews %>%
    filter(title == title) %>%
    unnest_tokens(ngram, review, token = "ngrams", n = 5) %>%
    separate(ngram, c("word1", "word2", "word3", "word4", "word5"), sep = " ") %>%
    anti_join(stop_words, by = c("word1" = "word")) %>%
    anti_join(stop_words, by = c("word2" = "word")) %>%
    anti_join(stop_words, by = c("word3" = "word")) %>%
    anti_join(stop_words, by = c("word4" = "word")) %>%
    anti_join(stop_words, by = c("word5" = "word")) %>%
    count(word1, word2, word3, word4, word5, sort = TRUE) %>%
    head(10)
  return(pentagram)
}

# A wrapper for the n gram functions
#
# @params title the movie title
# @params the number of tokens 
#
# returns the specified n gramm
getNGram <- function(title, n) {
  if(n == 2) {
    return(getReviewBigram(title))
  } else if (n == 3) {
    return(getReview3gram(title))
  } else if (n == 4) {
    return(getReview4gram(title))
  } else {
    return(getReview5gram(title))
  }
}


# Get the three most similar films based on IMDb reviews
#
# @params title film title
# @params n number of similar films (max=3)
#
# return a named list
getSimilarFilm <- function(film.title, n) {
  reviews.token <- IMDb.Ghibli.Reviews %>%
    unnest_tokens(word, review) %>%
    anti_join(stop_words) %>% 
    group_by(title) %>% 
    count(word, sort=TRUE)
  
  docsdissim <- proxy::dist(base::as.matrix(cast_dtm(reviews.token, title, word, n)), method = "cosine")
  sorted <- base::as.list(sort(base::as.matrix(docsdissim)[film.title,]))
  
  simfilm <- tibble(film = names(sorted), dissimilarity=unlist(sorted)) %>% 
    filter(film != film.title) %>% 
    mutate(similarity = 1 - dissimilarity) %>%
    mutate(film = factor(film, levels = film[order(similarity)])) %>%
    mutate(ranking = 1:n()) %>% 
    select(ranking, film, similarity) %>%
    head(n)
}


